CREATE DATABASE database_ucb

USE database_ucb


CREATE TABLE PLAYER(
ID			 INT		 IDENTITY(1, 1) NOT NULL PRIMARY KEY,
USERNAME	 VARCHAR(20)				NOT NULL,
PLAY_TIME	 DATETIME,
USER_LEVEL	 INT
)

INSERT INTO PLAYER(USERNAME, PLAY_TIME, USER_LEVEL)
VALUES('DaTrueBlueBowser', GETDATE(), 18)

CREATE TABLE ITEM(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
ITEM_DESCRIPTION VARCHAR(100) NOT NULL,
)

CREATE TABLE INVENTORY(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
UNLOCK_STATUS BINARY,
ID_PLAYER INT FOREIGN KEY REFERENCES PLAYER(ID),
ID_ITEM INT FOREIGN KEY REFERENCES ITEM(ID)
)

CREATE TABLE GAME_SERVER(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
CONECTION INT,
ID_PLAYER INT FOREIGN KEY REFERENCES PLAYER(ID)
)

CREATE TABLE PLAYER_SITUATION(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
POINTS INT,
HEALTH INT,
ID_INVENTORY INT FOREIGN KEY REFERENCES INVENTORY(ID)
)

CREATE TABLE ONLINE_MATCH(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
ID_PLAYER INT FOREIGN KEY REFERENCES PLAYER(ID),
ID_SITUATION INT FOREIGN KEY REFERENCES PLAYER_SITUATION(ID)
)


SELECT * FROM PLAYER
SELECT * FROM ITEM
SELECT * FROM INVENTORY
SELECT * FROM GAME_SERVER
SELECT * FROM PLAYER_SITUATION
SELECT * FROM ONLINE_MATCH

